# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

block_cipher = None

SRC_DIR = Path(SPECPATH) / "src"

a = Analysis(
    [str(SRC_DIR / "git_sync" / "cli.py")],
    pathex=[str(SRC_DIR)],
    binaries=[],
    datas=[
        ("config/git-sync.yaml.example", "config"),
    ],
    hiddenimports=[
        "git_sync",
        "git_sync.cli",
        "git_sync.core",
        "git_sync.core.git_ops",
        "git_sync.core.state_manager",
        "git_sync.core.author_rewrite",
        "git_sync.core.sync_engine",
        "git_sync.core.scheduler",
        "git_sync.models",
        "git_sync.models.config",
        "git_sync.models.state",
        "git_sync.models.sync",
        "git_sync.utils",
        "git_sync.utils.logger",
        "git_sync.utils.retry",
        "git_sync.utils.mailmap",
        "git_sync.tui",
        "git_sync.tui.app",
        "apscheduler",
        "apscheduler.schedulers",
        "apscheduler.schedulers.base",
        "apscheduler.schedulers.background",
        "apscheduler.triggers",
        "apscheduler.triggers.cron",
        "apscheduler.triggers.cron.fields",
        "apscheduler.executors",
        "apscheduler.executors.pool",
        "apscheduler.jobstores",
        "apscheduler.jobstores.memory",
        "textual",
        "textual.app",
        "textual.widget",
        "textual.widgets",
        "textual.containers",
        "textual.reactive",
        "textual.message",
        "textual.events",
        "textual.screen",
        "textual.layout",
        "textual.geometry",
        "rich",
        "rich.console",
        "rich.logging",
        "rich.pretty",
        "pydantic",
        "pydantic_core",
        "pydantic_core.core_schema",
        "yaml",
        "tenacity",
        "tenacity.retry",
        "tenacity.stop",
        "tenacity.wait",
    ],
    hookspath=["hooks"],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "PIL",
        "cv2",
        "torch",
        "tensorflow",
        "django",
        "flask",
        "fastapi",
        "sqlalchemy",
        "pytest",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="git-sync",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)